# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the directory
    directory: "/client"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    ignore:
      # Disable updating webpack until we migrate to v5
      - dependency-name: "webpack"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "pip"
    # Look for a requirements.txt in the directory
    directory: "/server"
    # Check for updates once a week
    schedule:
      interval: "weekly"      