openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://localhost
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /test:
    get:
      operationId: app.test
      summary: Test endpoint.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A test response
          content:
            application/json:
              schema: 
                type: string
  /patient_vitals:
    get:
      operationId: app.get_patient_vitals
      summary: Get the requested patient's vitals
      description: Endpoint that returns a list of a patient's vitals given optional parameters
      parameters:
        - name: user_id
          in: query
          required: true
          description: The ID of the user to return.
          schema:
            type: string
        - name: quantity
          in: query
          description: The quantity of data points to return. Returns up to 1 by default.
          schema:
            type: integer
            format: int64
            minimum: 0
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/patient_vitals'
        '400':
          description: The specified user_id is invalid.
        '404':
          description: The specified user_id was not found.
        default:
          description: An unspecified error occurred
    post:
      operationId: app.post_patient_vitals
      summary: Adds a new patient_vitals data point.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/patient_vitals'
      responses:
        '201':
          description: Created
        '409':
          description: The data point already exists for the specified user_id and date
    patch:
      operationId: app.patch_patient_vitals
      summary: Updates an exising patient_vitals data point.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/patient_vitals'
      responses:
        '200':
          description: Updated
        '404':
          description: The data point does not exist for the specified user_id and date
    delete:
      operationId: app.delete_patient_vitals
      summary: Deletes an existing patient_vitals data point.
      parameters:
        - name: user_id
          in: query
          required: true
          description: The ID of the users datapoint to delete.
          schema:
            type: string
        - name: entry_date
          in: query
          required: true
          description: The date of the datapoint to delete
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful deletion
        '400':
          description: The specified user_id is invalid.
        '404':
          description: The specified user_id was not found.
        default:
          description: An unspecified error occurred

components:
  schemas:
    patient_vitals:
      properties:
        user_id:
          type: string
        entry_date:
          type: string
          format: date
        systolic_pressure:
          type: integer
        diastolic_pressure:
          type: integer
        weight_in_kg:
          type: number
          format: float
        initial_drain:
          type: integer
        total_uf:
          type: integer
        average_dwell:
          type: string
        added_lost_dwell_type:
          type: string
        added_lost_dwell_value:
          type: string
        drain_color:
          type: string
        drain_clarity:
          type: string
        fibrin_present:
          type: string
        exit_color:
          type: string
        exit_sensitivity:
          type: string
        exit_condition:
          type: string
        bowel_obs:
          type: string
        treatment_problems:
          type: string
        comments:
          type: string
