openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://localhost
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /test:
    get:
      operationId: app.test
      summary: Test endpoint.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A test response
          content:
            application/json:
              schema: 
                type: string